In [11]:
import pandas as pd
import numpy as np

In [12]:
import nltk
nltk.download("punkt")
nltk.download("stopwords")

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\lipsa\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\lipsa\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

True

In [13]:
import pandas as pd
df = pd.read_csv(r"C:\Users\lipsa\OneDrive\Desktop\new_skills_dataset1.csv")

In [14]:
df.head()

             Role                                             Skills
0   Web Developer                       CSS*, Git, JavaScript, React
1    Data Analyst       Statistics##, Python@, Power BI, Excel, ~SQL
2  Cloud Engineer                     Networking, Linux, Python, AWS
3     AI Engineer  Python, NLP, PyTorch, Deep!! Learning, TensorF...
4   Web Developer        NodeJS&, Git, CSS*, JavaScript, React, HTML

In [15]:
df.shape

(1000, 2)

In [16]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Role    1000 non-null   str
 1   Skills  1000 non-null   str
dtypes: str(2)
memory usage: 15.8 KB

In [17]:
import nltk
from nltk.corpus import stopwords
from nltk.stem import PorterStemmer

In [18]:
stemmer = PorterStemmer()
stop_words = set(stopwords.words("english"))

In [19]:
import re
from nltk.tokenize import word_tokenize

In [20]:
def preprocess(text): 
    text=text.lower()
    text=re.sub(r'[^a-zA-Z]',' ', text)
    words=word_tokenize(text)
    processed_words = []
    for word in words:
        if word not in stop_words:
            processed_words.append(stemmer.stem(word))
            
    return" ".join(
        processed_words
)

In [21]:
df["Processed"] = df["Skills"].apply(preprocess)

In [22]:
df["Skills"].head()

0                         CSS*, Git, JavaScript, React
1         Statistics##, Python@, Power BI, Excel, ~SQL
2                       Networking, Linux, Python, AWS
3    Python, NLP, PyTorch, Deep!! Learning, TensorF...
4          NodeJS&, Git, CSS*, JavaScript, React, HTML
Name: Skills, dtype: str

In [23]:
df["Processed"].head()

0                             css git javascript react
1                    statist python power bi excel sql
2                              network linux python aw
3    python nlp pytorch deep learn tensorflow compu...
4                  nodej git css javascript react html
Name: Processed, dtype: str

In [24]:
from sklearn.feature_extraction.text import TfidfVectorizer
vectorizer = TfidfVectorizer()
X = vectorizer.fit_transform(df["Processed"])
print(X.shape)

(1000, 29)

In [25]:
print(X)

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 5809 stored elements and shape (1000, 29)>
  Coords	Values
  (0, 3)	0.5015330930141678
  (0, 7)	0.5005063805462119
  (0, 9)	0.49948535626515267
  (0, 22)	0.4984699574907663
  (1, 25)	0.4606014700407787
  (1, 20)	0.23214962326547112
  (1, 19)	0.44765485557529755
  (1, 1)	0.44765485557529755
  (1, 6)	0.46268916048347436
  (1, 24)	0.3450823663196805
  (2, 20)	0.29032320451629934
  (2, 14)	0.5527766902177993
  (2, 12)	0.5586380871738393
  (2, 0)	0.5459614045241625
  (3, 20)	0.20521095332502673
  (3, 15)	0.30194498744139725
  (3, 21)	0.39655727243741506
  (3, 4)	0.3957089328038007
  (3, 11)	0.2906048377868637
  (3, 27)	0.3957089328038007
  (3, 2)	0.3948656278564083
  (3, 28)	0.3948656278564083
  (4, 3)	0.40977908460673923
  (4, 7)	0.408940206173524
  (4, 9)	0.4081059752900958
  :	:
  (996, 20)	0.23214962326547112
  (996, 19)	0.44765485557529755
  (996, 1)	0.44765485557529755
  (996, 6)	0.46268916048347436
  (996, 24)	0.3450823663196805
  (997, 20)	0.20521095332502673
  (997, 15)	0.30194498744139725
  (997, 21)	0.39655727243741506
  (997, 4)	0.3957089328038007
  (997, 11)	0.2906048377868637
  (997, 27)	0.3957089328038007
  (997, 2)	0.3948656278564083
  (997, 28)	0.3948656278564083
  (998, 20)	0.25396262529128283
  (998, 14)	0.4835459834546467
  (998, 12)	0.48867328893927153
  (998, 0)	0.4775842559043126
  (998, 10)	0.48455955467789225
  (999, 25)	0.4178561981422269
  (999, 20)	0.2106054046446526
  (999, 19)	0.4061110704098292
  (999, 1)	0.4061110704098292
  (999, 6)	0.41975014431483776
  (999, 24)	0.3130576322813274
  (999, 26)	0.4207064218761507

In [26]:
import pandas as pd
tfidf_df = pd.DataFrame(
    X.toarray(),
    columns = vectorizer.get_feature_names_out()
)
tfidf_df.head()

,aw,bi,comput,css,deep,docker,excel,git,html,javascript,...,power,python,pytorch,react,scikit,sql,statist,tableau,tensorflow,vision
0,0.000000,0.000000,0.000000,0.501533,0.000000,0.0,0.000000,0.500506,0.000000,0.499485,...,0.000000,0.000000,0.000000,0.498470,0.0,0.000000,0.000000,0.0,0.000000,0.000000
1,0.000000,0.447655,0.000000,0.000000,0.000000,0.0,0.462689,0.000000,0.000000,0.000000,...,0.447655,0.232150,0.000000,0.000000,0.0,0.345082,0.460601,0.0,0.000000,0.000000
2,0.545961,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.290323,0.000000,0.000000,0.0,0.000000,0.000000,0.0,0.000000,0.000000
3,0.000000,0.000000,0.394866,0.000000,0.395709,0.0,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.205211,0.396557,0.000000,0.0,0.000000,0.000000,0.0,0.395709,0.394866
4,0.000000,0.000000,0.000000,0.409779,0.000000,0.0,0.000000,0.408940,0.408106,0.408106,...,0.000000,0.000000,0.000000,0.407276,0.0,0.000000,0.000000,0.0,0.000000,0.000000

In [27]:
from sklearn.preprocessing import LabelEncoder
encoder = LabelEncoder()
y = encoder.fit_transform(df["Role"])

In [28]:
print(y)

[4 2 1 0 4 2 2 4 3 3 4 2 3 2 1 4 1 3 1 0 0 0 3 2 1 3 0 2 0 3 4 1 0 3 0 4 4
 3 2 2 4 1 4 3 1 2 0 4 3 0 4 4 2 1 0 1 2 3 0 4 2 3 1 4 2 2 3 1 1 1 3 2 1 1
 2 0 1 2 1 0 3 2 1 0 2 3 1 0 3 4 4 3 1 2 0 0 4 1 3 0 1 2 2 4 0 0 4 2 3 3 4
 4 4 0 2 0 2 1 4 4 0 3 3 0 1 2 2 3 3 2 2 2 4 1 3 2 0 3 1 0 1 0 1 4 2 3 0 1
 2 4 4 2 0 3 4 1 0 0 4 1 4 1 1 4 1 2 4 0 2 1 3 4 2 1 3 1 4 0 4 4 0 4 4 0 2
 3 1 2 1 0 3 1 0 3 3 3 3 4 4 0 2 0 1 2 2 1 2 4 4 3 2 4 2 3 1 4 2 0 3 0 1 1
 4 1 3 3 1 2 3 4 4 1 4 4 2 1 2 3 1 1 3 4 4 3 3 0 3 4 4 0 1 2 3 2 1 0 1 0 4
 2 0 4 4 1 2 0 1 0 0 0 4 1 1 1 1 2 2 3 3 2 3 1 0 4 3 4 0 2 2 4 4 2 1 2 1 4
 0 3 3 1 0 3 3 3 0 2 1 3 3 4 1 0 3 2 0 4 2 3 2 1 1 1 4 1 3 4 2 4 1 0 3 4 3
 0 2 0 0 0 2 4 0 0 2 4 0 0 3 2 1 0 3 1 4 4 1 4 4 3 0 4 2 3 0 2 4 0 0 0 2 2
 2 4 4 4 3 1 2 1 4 0 1 2 2 4 1 3 2 3 2 0 1 2 4 4 3 0 3 3 1 2 3 2 2 0 3 4 4
 1 4 1 0 2 3 1 2 1 2 4 3 1 1 0 1 2 2 0 3 0 4 3 1 4 2 3 0 0 0 4 1 0 0 4 2 1
 2 3 1 2 0 3 4 1 1 4 0 2 1 2 4 4 1 0 1 1 0 1 3 3 0 1 3 4 4 1 3 0 1 3 4 3 1
 0 0 2 4 2 0 0 1 2 4 2 1 1 0 1 3 4 4 4 1 2 3 2 3 2 0 3 1 4 2 2 4 3 3 1 4 4
 1 1 0 1 0 1 3 3 0 4 4 0 1 0 0 2 0 4 3 3 0 3 4 3 4 3 4 0 4 4 3 4 3 0 1 4 0
 3 1 2 3 2 2 0 1 4 0 3 4 0 3 1 3 2 3 4 1 2 0 0 4 0 0 4 0 1 2 3 4 0 0 0 1 2
 0 4 4 3 1 4 1 2 2 0 3 1 2 1 1 0 2 4 4 3 3 2 4 3 0 1 1 0 4 2 0 1 1 4 4 4 0
 2 4 2 0 4 4 0 0 4 2 2 3 4 0 0 2 0 4 1 2 2 1 2 3 3 0 4 4 1 4 1 4 1 1 2 1 3
 4 4 0 2 1 0 0 0 4 0 4 0 3 0 1 0 4 0 3 3 3 4 3 0 3 0 3 0 1 1 1 4 4 2 2 2 1
 0 3 2 0 4 3 2 0 0 4 4 3 4 0 4 0 1 2 0 3 4 2 1 2 4 1 2 0 2 3 4 2 1 1 4 3 0
 3 0 3 2 1 1 3 4 1 2 4 4 4 0 1 0 0 1 0 0 1 0 4 3 4 3 2 2 1 0 3 4 1 4 1 0 4
 3 2 1 2 1 3 1 1 2 2 1 3 1 2 4 4 2 1 0 0 3 2 2 4 3 2 3 0 0 3 1 0 2 0 3 1 1
 3 4 3 3 4 4 1 2 4 1 2 0 3 2 2 2 1 0 1 4 4 4 4 2 2 3 3 3 4 3 4 1 4 4 3 0 2
 1 2 2 1 4 3 1 4 3 1 1 3 3 1 0 0 3 3 2 3 0 0 2 4 0 2 0 4 0 0 1 4 2 4 0 3 3
 4 1 0 1 0 0 1 3 4 3 1 2 0 3 4 3 3 1 0 4 1 2 2 0 2 3 1 1 4 3 2 2 3 0 0 3 2
 3 1 2 0 2 3 2 1 3 3 1 3 1 1 0 4 0 4 0 3 1 0 2 4 4 1 4 2 0 3 4 3 2 3 1 3 4
 4 2 4 2 3 0 1 4 3 2 4 3 0 0 1 1 3 4 4 3 0 4 2 0 4 2 0 4 1 4 1 3 1 4 2 0 1
 2]

In [29]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2,random_state=42)

In [30]:
from sklearn.naive_bayes import MultinomialNB
model = MultinomialNB()
model.fit(X_train, y_train)

MultinomialNB()

In [31]:
predictions = model.predict(X_test)

In [32]:
from sklearn.metrics import accuracy_score
accuracy = accuracy_score(y_test, predictions)
print("Accuracy:",round(accuracy*100,2),"%")

Accuracy: 100.0 %

In [33]:
import pickle

In [34]:
pickle.dump(
    model,
    open("model.pkl","wb")
)
pickle.dump(
    vectorizer,
    open("vectorizer.pkl","wb")
)
pickle.dump(
    encoder,
    open("encoder.pkl","wb")
)

In [35]:
skills = """
Python
SQL
"""
processed = preprocess(
    skills
)
vector = vectorizer.transform(
    [processed]
)
prediction = model.predict(
    vector
)
role = encoder.inverse_transform(
    prediction
)
print(
    "Predicted Role:", role[0]
)

Predicted Role: Data Analyst

In [36]:
import ipywidgets as widgets
from IPython.display import display, HTML
import pickle
import re
model = pickle.load(open("model.pkl","rb"))
vectorizer = pickle.load(open("vectorizer.pkl","rb"))
encoder = pickle.load(open("encoder.pkl","rb"))

In [37]:
skills_box = widgets.Textarea(
    placeholder="Example:\nPython\nSQL\nMachine Learning\nPandas\nNLP",
    layout=widgets.Layout(
        width="800px",
        height="200px"
    )
)

In [38]:
predict_btn = widgets.Button(
    description="Predict Career",
    button_style='success',
    icon='search'
)
clear_btn = widgets.Button(
    description="Clear",
    button_style='warning',
    icon='trash'
)

In [39]:
output = widgets.Output()

In [40]:
def predict_role(b):

    with output:

        output.clear_output()

        skills = skills_box.value   # taking the inputs as skill names

        processed = preprocess(skills)

        vector = vectorizer.transform([processed])

        prediction = model.predict(vector)

        role = encoder.inverse_transform(prediction)[0]

        confidence = round(
            max(model.predict_proba(vector)[0]) * 100,
            2
        )

        display(HTML(f"""
        <div style="
            border:2px solid #10B981;
            padding:20px;
            border-radius:10px;
            margin-top:10px;">

            <h2>🎯 Prediction Result</h2>

            <h3>Predicted Role:</h3>
            <h1 style='color:#4F46E5'>
                {role}
            </h1>

            <h3>Confidence:</h3>
            <h2 style='color:green'>
                {confidence}%
            </h2>

        </div>
        """))

In [41]:
predict_btn.on_click(predict_role)

display(
    widgets.VBox([
        widgets.HTML("<h3>📋 Enter Your Skills</h3>"),
        skills_box,
        widgets.HBox([
            predict_btn,
            clear_btn
        ]),
        output
    ])
)

VBox(children=(HTML(value='<h3>📋 Enter Your Skills</h3>'), Textarea(value='', layout=Layout(height='200px', wi…